var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(auth)/login/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sbx-ty._.js")
R.c("server/chunks/ssr/08if_next_dist_20cefy9._.js")
R.c("server/chunks/ssr/08if_next_dist_esm_build_templates_app-page_1zxr_y6.js")
R.c("server/chunks/ssr/[root-of-the-server]__12rpi7w._.js")
R.c("server/chunks/ssr/[root-of-the-server]__010yfzt._.js")
R.c("server/chunks/ssr/08if_next_dist_compiled_@opentelemetry_api_index_1lelwkq.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p7s-5f._.js")
R.c("server/chunks/ssr/08if_next_dist_client_components_03uwi7r._.js")
R.c("server/chunks/ssr/08if_next_dist_client_components_builtin_forbidden_1ipqm49.js")
R.c("server/chunks/ssr/08if_next_dist_client_components_builtin_unauthorized_0zaggwp.js")
R.c("server/chunks/ssr/08if_next_dist_client_components_builtin_global-error_1qzcqho.js")
R.c("server/chunks/ssr/OneDrive_Documents_AssetFlow_1usu7g7._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0sdam5g._.js")
R.c("server/chunks/ssr/OneDrive_Documents_AssetFlow_0vfgvvv._.js")
R.c("server/chunks/ssr/08if_next_dist_1l5ms22._.js")
R.m(23606)
module.exports=R.m(23606).exports
