var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/(dashboard)/allocations/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__12vi88a._.js")
R.c("server/chunks/ssr/OneDrive_Documents_AssetFlow_1usu7g7._.js")
R.c("server/chunks/ssr/08if_next_dist_esm_build_templates_app-page_1vj6e0x.js")
R.c("server/chunks/ssr/08if_next_dist_20cefy9._.js")
R.c("server/chunks/ssr/08if_next_dist_1zamwwp._.js")
R.c("server/chunks/ssr/[root-of-the-server]__12rpi7w._.js")
R.c("server/chunks/ssr/[root-of-the-server]__010yfzt._.js")
R.c("server/chunks/ssr/08if_next_dist_compiled_@opentelemetry_api_index_1lelwkq.js")
R.c("server/chunks/ssr/[root-of-the-server]__0p7s-5f._.js")
R.c("server/chunks/ssr/08if_next_dist_client_components_03uwi7r._.js")
R.c("server/chunks/ssr/08if_next_dist_client_components_builtin_forbidden_1ipqm49.js")
R.c("server/chunks/ssr/08if_next_dist_client_components_builtin_unauthorized_0zaggwp.js")
R.c("server/chunks/ssr/08if_next_dist_client_components_builtin_global-error_1qzcqho.js")
R.c("server/chunks/ssr/OneDrive_Documents_AssetFlow_src_0o4oa4s._.js")
R.c("server/chunks/ssr/0dp3__next-internal_server_app_(dashboard)_allocations_page_actions_02b4-v-.js")
R.m(31912)
module.exports=R.m(31912).exports
